[package]
name = "dnd-stats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
rand = { version = "0.7", features = ["wasm-bindgen"] }
